var WebSwift = function (n) {
    "use strict"
    const t = function (n) {
        class t extends HTMLElement {
            static define() { customElements.define(n.name, this) } #n = {}
            static observedAttributes = Object.keys(n.props ?? {})
            constructor() {
                super()
                const t = this.attachShadow({ mode: "open" }); ((n, t = "") => {
                    const e = new CSSStyleSheet
                    e.replaceSync(t), n.adoptedStyleSheets.push(e)
                })(t, n.style), t.innerHTML = n.template || ""
                for (const e in n.props || {}) { const i = this.getAttribute(e); this.#n[e] = i || n.props[e]; if (null == i && n.syncProps?.includes(e)) this.setAttribute(e, this.#n[e]) }
                for (const t in n.props) Object.defineProperty(this, t, { get: () => this.#n[t], set: e => { this.#n[t] != e && (this.#n[t] = e, this.getAttribute(t) != e && n.syncProps?.includes(t) && this.setAttribute(t, e), n.dispatch?.attrchanges.call(this, t, e)) } })
                n.setup?.call(this, t)
            } attributeChangedCallback(t, e, i) { if (e !== i && this.#n[t] !== i) this[t] = i ?? "" }
        } return t
    }
    class e extends (t({
        name: "c-button", template: "<p><slot></slot></p><div gradient></div><div fill></div>", style: ':host {\n  width: auto;\n  height: auto;\n  border-radius: 5px;\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  width: auto;\n  height: auto;\n  padding: 3px 7px;\n  overflow: hidden;\n  position: relative;\n  cursor: default;\n  -webkit-user-select: none;\n     -moz-user-select: none;\n          user-select: none;\n  border: 0.5px solid rgba(0, 0, 0, 0.02);\n  box-shadow: 0 0 0 rgba(0, 0, 0, 0.15), 0 1px 0 rgba(0, 0, 0, 0.05);\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n}\n:host [gradient] {\n  width: 100%;\n  height: 100%;\n  display: none;\n  position: absolute;\n  top: 0;\n  left: 0;\n  z-index: -1;\n}\n:host [fill] {\n  width: 100%;\n  height: 100%;\n  background: #fff;\n  position: absolute;\n  top: 0;\n  left: 0;\n  z-index: -2;\n}\n:host p {\n  color: black;\n  font-size: 13px;\n  margin: 0;\n}\n:host([primary]) {\n  box-shadow: 0 0.5px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.12), 0 0.5px 1px rgba(0, 0, 0, 0.24);\n  border: none;\n}\n:host([primary]) p {\n  color: white;\n}\n:host([primary]) [gradient] {\n  display: block;\n  background: linear-gradient(to bottom, #fff, rgba(255, 255, 255, 0));\n  opacity: 0.17;\n}\n:host([primary]) [fill] {\n  background: #007aff;\n}\n:host([disabled=true]) {\n  box-shadow: 0 0 0 rgba(0, 0, 0, 0.15), 0 1px 0 rgba(0, 0, 0, 0.05);\n  pointer-events: none;\n}\n:host([disabled=true]) [gradient] {\n  display: none;\n}\n:host([disabled=true]) [fill] {\n  background: #fff;\n}\n:host([disabled=true]) p {\n  color: rgba(0, 0, 0, 0.25);\n}', props: { disabled: "false", command: "" }, syncProps: ["disabled", "command"], setup(n) {
            setTimeout((() => {
                const n = new Function(this.command)
                let t
                this.addEventListener("mousedown", (() => { t = !0, this.style.filter = "brightness(0.9)" })), window.addEventListener("mouseup", (() => { t && (t = !1, this.style.filter = "brightness(1)", n()) }))
            }))
        }
    })) { } e.define()
    const i = { iconpath: "" }
    class o extends (t({
        name: "c-messagebox", template: '<img icon />\n        <slot name="title"></slot>\n        <slot name="text"></slot>\n        <slot name="button"></slot>', style: '@keyframes Pop {\n  0% {\n    opacity: 0;\n    box-shadow: none;\n    transform: scale(0.1);\n  }\n  50% {\n    transform: scale(0.5);\n    opacity: 0.2;\n  }\n  80% {\n    transform: scale(1.1);\n    opacity: 0.3;\n  }\n}\n:host {\n  display: inline-flex;\n  flex-direction: column;\n  align-items: center;\n  justify-content: center;\n  width: 228px;\n  height: auto;\n  box-shadow: inset 0 0 3px rgba(255, 255, 255, 0.1), 0 0 2px rgba(0, 0, 0, 0.05), 0 38px 90px rgba(0, 0, 0, 0.25), 0 0 1px rgba(0, 0, 0, 0.6);\n  border-radius: 10px;\n  background: rgba(246, 246, 246, 0.6);\n  -webkit-backdrop-filter: blur(30px);\n          backdrop-filter: blur(30px);\n  padding: 20px 16px;\n  padding-bottom: 16px;\n  animation: Pop 0.3s linear forwards;\n  transform-origin: center;\n  position: fixed;\n  top: 50%;\n  left: 50%;\n  opacity: 1;\n  transform: scale(1);\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n}\n:host img[icon] {\n  width: 64px;\n  height: 64px;\n  margin-bottom: 20px;\n}\n::slotted([slot=title]) {\n  font-size: 13px;\n  margin: 0;\n  margin-bottom: 10px;\n  font-family: "SFPro-Semibold", "PingFangSC-Semibold";\n}\n::slotted([slot=text]) {\n  font-size: 11px;\n  margin: 0;\n  margin-bottom: 16px;\n  text-align: center;\n}\n::slotted([slot=button]) {\n  height: 23px;\n  align-self: normal;\n}', props: i, syncProps: ["iconpath"], setup(n) {
            console.log(111), setTimeout((() => {
                const t = n.querySelector("img")
                t.src = this.iconpath, console.log(t, this.iconpath)
            }))
        }
    })) { } o.define()
    class s extends (t({
        name: "c-checkbox", template: '<div type>\n    <img draggable="false" mark src="./assets/uitick.svg" />\n    <div gradient></div>\n    <div fill></div>\n</div>\n<p label>Hello</p>', style: ':host {\n  width: auto;\n  height: auto;\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  -webkit-user-select: none;\n     -moz-user-select: none;\n          user-select: none;\n  cursor: default;\n}\n:host div[type] {\n  width: 14px;\n  height: 14px;\n  position: relative;\n}\n:host div[type] img[mark] {\n  width: 100%;\n  height: 100%;\n  position: absolute;\n  top: 0;\n  left: 0;\n  z-index: 1;\n  scale: 0.8;\n  display: none;\n}\n:host div[type] div[gradient] {\n  opacity: 0.17;\n  position: absolute;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  border-radius: 3.5px;\n  z-index: -1;\n  display: none;\n}\n:host div[type] div[fill] {\n  position: absolute;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  z-index: -2;\n  background: #FFFFFF;\n  border: 0.5px solid rgba(0, 0, 0, 0.15);\n  box-shadow: inset 0 1px 2px 0 rgba(0, 0, 0, 0.1), inset 0 0 2px 0 rgba(0, 0, 0, 0.1);\n  border-radius: 3.5px;\n}\n:host([state=on]) div[type] img[mark] {\n  display: initial;\n}\n:host([state=on]) div[type] div[gradient] {\n  display: block;\n  background: linear-gradient(180deg, #FFFFFF 0%, rgba(255, 255, 255, 0) 96%);\n}\n:host([state=on]) div[type] div[fill] {\n  border: none;\n  background: #007aff;\n  box-shadow: 0 0 3px 0 rgba(255, 255, 255, 0.12), 0 1px 2px 0 rgba(255, 255, 255, 0.12), 0 0 1px 0 rgba(255, 255, 255, 0.24);\n}\n:host([disabled=true][state=on]) img[mark] {\n  opacity: 0.25 !important;\n  filter: invert(1);\n}\n:host([disabled=true][state=on]) div[gradient] {\n  display: none;\n}\n:host([disabled=true][state=on]) div[fill] {\n  opacity: 0.5 !important;\n  background: #FFFFFF !important;\n  border: 0.5px solid rgba(0, 0, 0, 0.02) !important;\n  box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.15), 0 1px 0 0 rgba(0, 0, 0, 0.05) !important;\n}\n:host([disabled=true][state=off]) div[fill] {\n  opacity: 0.49;\n  background: #FFFFFF;\n  border: 0.5px solid rgba(0, 0, 0, 0.15);\n  box-shadow: inset 0 1px 2px 0 rgba(0, 0, 0, 0.1), inset 0 0 2px 0 rgba(0, 0, 0, 0.1);\n}\n:host([disabled=true]){\n  pointer-events:none;\n}\n:host p[label] {\n  margin: 0;\n  margin-left: 6px;\n  font-size: 13px;\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n}', props: { state: "on", disabled: "false" }, syncProps: ["state", "disabled"], setup(n) {
            let t
            this.addEventListener("mousedown", (() => { t = !0, this.style.filter = "brightness(0.9)" })), window.addEventListener("mouseup", (() => { t && (t = !1, this.state = "on" == this.state ? "off" : "on", this.style.filter = "brightness(1)") }))
        }
    })) { } s.define()
    class a extends (t({
        name: "c-window", template: '<div titlebar>\n    <div wintools>\n        <div oval close>\n            <img src="../assets/uixmark.svg" />\n        </div>\n        <div oval minimize>\n            <img src="../assets/uiminus.svg" />\n        </div>\n        <div oval zoom>\n            <img src="../assets/uiarrow.up.left.and.arrow.down.right.svg" />\n        </div>\n    </div>\n    <p title></p>\n</div>\n<div content><slot></slot></div>', style: ':host {\n  width: 400px;\n  height: 300px;\n  background: #fff;\n  box-shadow: 0 36px 100px 0 rgba(0, 0, 0, 0.35), 0 0 3px 0 rgba(0, 0, 0, 0.23), inset 0 0 3px 0 rgba(255, 255, 255, 0.1);\n  border-radius: 10px;\n  overflow: hidden;\n  display: block;\n  min-width: 86px;\n  min-height: 38px;\n  resize: both;\n}\n:host::-webkit-resizer {\n  display: none;\n}\n:host div[titlebar] {\n  width: 100%;\n  height: 28px;\n  position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  background: rgb(245, 245, 245);\n  box-shadow: 0 1px 0 0 rgba(0, 0, 0, 0.15);\n  cursor: default;\n  user-select: none;\n  -webkit-user-select: none;\n}\n:host div[titlebar] div[wintools] {\n  width: auto;\n  height: 12px;\n  display: inline-flex;\n  position: absolute;\n  top: 8px;\n  left: 0;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  padding-left: 8px;\n}\n:host div[titlebar] div[wintools]:hover div[oval] img {\n  display: initial;\n}\n:host div[titlebar] div[wintools] div[oval] {\n  width: 12px;\n  height: 12px;\n  border-radius: 6px;\n  margin-right: 8px;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n:host div[titlebar] div[wintools] div[oval] img {\n  width: 100%;\n  height: 100%;\n  scale: 0.5;\n  display: none;\n}\n:host div[titlebar] div[wintools] div[close] {\n  background: #ff5f57;\n  border: 0.5px solid rgba(0, 0, 0, 0.2);\n}\n:host div[titlebar] div[wintools] div[minimize] {\n  background: #febc2e;\n  border: 0.5px solid rgba(0, 0, 0, 0.2);\n}\n:host div[titlebar] div[wintools] div[zoom] {\n  background: #28c840;\n  border: 0.5px solid rgba(0, 0, 0, 0.2);\n}\n:host div[titlebar] p[title] {\n  font-size: 13px;\n  font-family: "SFPro-Semibold", "PingFangSC-Semibold";\n  max-width: 40%;\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n}\n:host div[content] {\n  width: 100%;\n  height: 100%;\n}', props: { title: "", width: 0, height: 0 }, syncProps: ["title", "width", "height"], setup(n) {
            setTimeout((() => {
                let t = this.title
                n.querySelector("p[title]").innerHTML = t
                let e = this.width, i = this.height
                this.style.width = e + "px", this.style.height = i + "px"
            }))
            let t
            n.querySelectorAll("div[oval]").forEach((n => { n.addEventListener("mousedown", (() => { n.style.filter = "brightness(0.9)", t = !0 })), window.addEventListener("mouseup", (() => { t && (t = !1, n.style.filter = "brightness(1)", n.hasAttribute("close") && this.parentNode?.removeChild(this)) })) }))
        }
    })) { } a.define()
    class r extends (t({
        name: "c-switch", template: "<div oval></div><div fill></div>", style: ":host {\n  width: 26px;\n  height: 15px;\n  position: relative;\n  display: block;\n}\n:host div[oval] {\n  background: #fff;\n  width: 12px;\n  height: 12px;\n  border-radius: 6.5px;\n  position: absolute;\n  transition: all 0.25s ease;\n  box-sizing: border-box;\n}\n:host div[fill] {\n  width: 100% ;\n  height: 100%;\n  border-radius: 11px;\n  position: absolute;\n  top: 0;\n  left: 0;\n  z-index: -1;\n  transition: all 0.25s ease;\n}\n:host([state=on]) div[oval] {\n  border: 0.5px solid rgba(0, 0, 0, 0.02);\n  box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.15);\n  left: calc(100% - 1.5px - 12px);\n  right: 1.5px;\n  top: 1.5px;\n}\n:host([state=on]) div[fill] {\n  background: #2c7af1;\n  box-shadow: inset 0 3px 4px 0 rgba(0, 0, 0, 0.1), inset 0 0 2px 0 rgba(0, 0, 0, 0.05);\n}\n:host([state=off]) div[oval] {\n  right: calc(100% - 1.5px - 12px);\n  left: 1.5px;\n  top: 1.5px;\n  box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.15), 0 1px 0 0 rgba(0, 0, 0, 0.05);\n}\n:host([state=off]) div[fill] {\n  background: rgba(0, 0, 0, 0.1);\n  box-shadow: inset 0 0 1px 0 rgba(0, 0, 0, 0.02), inset 0 0 1px 0 rgba(0, 0, 0, 0.12);\n}\n:host([disabled=true]) {\n  pointer-events: none;\n}\n:host([disabled=true]) div[oval] {\n  box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.15), 0 1px 0 0 rgba(0, 0, 0, 0.05);\n  pointer-events: none;\n}\n:host([disabled=true]) div[fill] {\n  background: rgba(0, 0, 0, 0.1);\n  box-shadow: inset 0 0 1px 0 rgba(0, 0, 0, 0.02), inset 0 0 1px 0 rgba(0, 0, 0, 0.12);\n  pointer-events: none;\n}", props: { state: "on", disabled: "false" }, syncProps: ["state", "disabled"], setup(n) {
            let t
            this.addEventListener("mousedown", (() => { this.style.filter = "brightness(0.9)", t = !0 })), window.addEventListener("mouseup", (() => { t && (t = !1, this.style.filter = "brightness(1)", this.state = "on" == this.state ? "off" : "on") }))
        }
    })) { } r.define()
    class l extends (t({
        name: "c-progress", template: "<div fill></div><div back></div>", style: ":host {\n  width: 100px;\n  height: 6px;\n  border-radius: 3px;\n  overflow: hidden;\n  display: inline-block;\n  position: relative;\n}\n:host div[fill] {\n  width: 0%;\n  height: 100%;\n  background: #007aff;\n  position: absolute;\n  top: 0;\n  left: 0;\n  border-radius: 3px;\n  transition: width 0.3s ease;\n}\n:host div[back] {\n  width: 100%;\n  height: 100%;\n  background: rgba(0, 0, 0, 0.05);\n  position: absolute;\n  top: 0;\n  left: 0;\n}\n:host([small]) {\n  height: 3px;\n}", props: { small: "", progress: "" }, syncProps: ["small", "progress"], setup(n) { setTimeout((() => { n.querySelector("div[fill]").style.width = `${this.progress}%` })) }, dispatch: {
            attrchanges(n, t) {
                if ("progress" == n) {
                    const n = this.shadowRoot?.querySelector("div[fill]")
                    n.style.width = `${t}%`
                }
            }
        }
    })) { } l.define()
    class d extends (t({
        name: "c-input", template: '<img icon src="./assets/uisearch.svg" />\n<input />\n<img clear src="./assets/uixmark.circle.fill.svg" />\n<div fill></div>', style: ':host {\n  width: 206px;\n  height: 22px;\n  position: relative;\n  display: inline-flex;\n  align-items: center;\n}\n:host img[icon] {\n  display: none;\n}\n:host input {\n  width: calc(100% - 14px);\n  height: 100%;\n  background: transparent;\n  border: none;\n  outline: none;\n  position: absolute;\n  top: 0;\n  left: 0;\n  z-index: 0;\n  padding: 0 7px;\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n}\n:host input:focus ~ div[fill] {\n  outline: 3px solid rgba(0, 122, 255, 0.5);\n}\n:host input:focus ~ img[clear] {\n  opacity: 0.25;\n  pointer-events: initial;\n}\n:host input::-moz-placeholder {\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n  font-size: 13px;\n  color: rgba(0, 0, 0, 0.25);\n  line-height: 16px;\n}\n:host input::placeholder {\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n  font-size: 13px;\n  color: rgba(0, 0, 0, 0.25);\n  line-height: 16px;\n}\n:host div[fill] {\n  width: 100%;\n  height: 100%;\n  position: absolute;\n  top: 0;\n  left: 0;\n  z-index: -2;\n  outline: 6px solid transparent;\n  transition: outline 0.3s ease;\n  pointer-events: none;\n  background: #fff;\n  box-shadow: 0 0 2px 0 rgba(0, 0, 0, 0.3), 0 0 0 0 rgba(0, 0, 0, 0.05);\n}\n:host img[clear] {\n  opacity: 0;\n  position: absolute;\n  right: 3px;\n  top: 3px;\n  pointer-events: none;\n  width: 16px;\n  height: 16px;\n  transition: opacity 0.25s ease;\n}\n:host([type=search]) img[icon] {\n  display: block;\n  margin-left: 7px;\n}\n:host([type=search]) input {\n  width: calc(100% - 35px);\n  padding-left: 28px;\n}\n:host([type=search]) div[fill] {\n  background: #fff;\n  box-shadow: 0 0 2px 0 rgba(0, 0, 0, 0.3), 0 0 0 0 rgba(0, 0, 0, 0.05);\n  border-radius: 5px;\n}\n:host([disabled=true]) { pointer-events: none }\n:host([disabled=true]) div[fill] {\n  background: rgba(255, 255, 255, 0.5) !important;\n}\n:host([disabled=true][type=search]) img[icon] {\n  opacity: 0.5;\n}', props: { type: "", disabled: "false", placeholder: "", value: "" }, syncProps: ["type", "disabled", "placeholder", "value"], setup(n) {
            const t = n.querySelector("img[clear]"), e = n.querySelector("input")
            this.value = e?.value, this.placeholder = e?.placeholder, e.value = this.value, e.placeholder = this.placeholder, t?.addEventListener("mousedown", (() => { t.style.filter = "brightness(0.9)", e.focus(), e.value = "", this.value = e.value })), t?.addEventListener("mouseup", (() => { t.style.filter = "brightness(1)", e.focus(), e.value = "", this.value = e.value }))
        }
    })) { } d.define()
    class p extends (t({
        name: "c-notification", template: '<img /><div>\n    <slot name="title"></slot>\n    <slot name="text"></slot>\n</div>\n<slot name="time"></slot>', style: '@keyframes in {\n  0% {\n    transform: translateX(400px);\n    opacity: 0;\n  }\n  75% {\n    transform: translateX(0);\n  }\n  100% {\n    opacity: 1;\n  }\n}\n@keyframes out {\n  0% {\n    transform: translateX(0);\n    opacity: 1;\n  }\n  75% {\n    transform: translateX(400px);\n  }\n  100% {\n    opacity: 0;\n  }\n}\n:host {\n  width: 346px;\n  height: 76px;\n  background: rgba(246, 246, 246, 0.6);\n  border-radius: 16px;\n  box-shadow: 0 8px 40px 0 rgba(0, 0, 0, 0.25), 0 0 3px 0 rgba(0, 0, 0, 0.55);\n  display: flex;\n  align-items: center;\n  position: absolute;\n  top: 10px;\n  right: 10px;\n  -webkit-user-select: none;\n     -moz-user-select: none;\n          user-select: none;\n  cursor: default;\n  -webkit-backdrop-filter: blur(30px);\n          backdrop-filter: blur(30px);\n  animation: in 0.4s ease;\n}\n:host(.close) { animation: out 0.4s ease forwards }\n:host img {\n  width: 40px;\n  height: 40px;\n  margin-left: 10px;\n  margin-right: 8px;\n}\n::slotted([slot=title]) {\n  font-family: "SFPro-Semibold", "PingFangSC-Semibold";\n  font-size: 13px;\n  color: rgba(0, 0, 0, 0.85);\n  line-height: 16px;\n  margin: 0;\n}\n::slotted([slot=text]) {\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n  font-size: 13px;\n  margin-top: 1.5px;\n  color: rgba(0, 0, 0, 0.85);\n  line-height: 16px;\n  width: 255px;\n  margin: 0;\n}\n::slotted([slot=time]) {\n  position: absolute;\n  font-family: "SFPro-Regular", "PingFangSC-Regular";\n  font-size: 11px;\n  color: #0009;\n  line-height: 14px;\n  align-self: flex-start;\n  margin: 0;\n  top: 12px;\n  right: 14px;\n}', props: { command: "", iconpath: "" }, syncProps: ["command", "iconpath"], setup(n) {
            const t = n.querySelector("img"), e = new Function(this.command)
            let i
            t.src = this.iconpath, this.addEventListener("mousedown", (() => { i = !0, this.style.filter = "brightness(0.9)" })), window.addEventListener("mouseup", (() => { i && (i = !1, this.style.filter = "brightness(1)", e()) }))
        }
    })) { } return p.define(), n.Button = e, n.CheckBox = s, n.MessageBox = o, n.Switch = r, n.Window = a, n
}({})
